/**
 * The phone's matcher against the desktop's, case for case.
 *
 * `src/lib/identify.ts` is a port of the exact-key half of `scanner.py`, and
 * a port is only worth anything if it agrees with the original. The regexes
 * it carries are not decorative — each one records a card that was filed
 * wrong until it was fixed, and re-deriving them by eye on a second platform
 * is how you get those bugs back one at a time.
 *
 * So the expectations here are not hand-written. `fixtures/identify-corpus
 * .json` was generated by running the real Python functions over 400 real
 * printings from the real catalogue, in seven renderings each — clean, foil
 * star, separator eaten, bare number, mirrored OCR debris, a leading O for a
 * zero, and a footer with no name above it. If the two implementations ever
 * disagree about any of those, this fails.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, test } from 'node:test';

import {
  collectorNumbersIn,
  footerKeys,
  NAME_SHORTLIST,
  identifyLocally,
  looksLikeSetCode,
  normaliseNumber,
  parseFooter,
  promoKey,
  repairDigits,
  setCodeVariants,
} from '../src/lib/identify.ts';

const load = (name) =>
  JSON.parse(readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf8'));

const CORPUS = load('identify-corpus.json');
const HELPERS = load('identify-helpers.json');

describe('the small pieces agree with Python', () => {
  test('collector numbers normalise identically', () => {
    for (const [input, expected] of Object.entries(HELPERS.normalise)) {
      assert.equal(normaliseNumber(input), expected, `normalise(${input})`);
    }
  });

  test('digit repair leaves words alone identically', () => {
    // The one that matters: "MID-2I1" must NOT become "M10-211", which is a
    // real PLST number for a different card and auto-added it.
    for (const [input, expected] of Object.entries(HELPERS.repair)) {
      assert.equal(repairDigits(input), expected, `repair(${input})`);
    }
  });

  test('set-code capitalisation is judged identically', () => {
    for (const [input, expected] of Object.entries(HELPERS.setcode)) {
      assert.equal(looksLikeSetCode(input), expected, `looksLike(${input})`);
    }
  });

  test('set-code variants are generated identically', () => {
    for (const [input, expected] of Object.entries(HELPERS.variants)) {
      assert.deepEqual(setCodeVariants(input), expected, `variants(${input})`);
    }
  });
});

describe('the footer parse agrees across 2800 real cases', () => {
  test('collector number', () => {
    const bad = CORPUS.filter(
      (c) => parseFooter(c.text).collectorNumber !== c.expect.collector_number);
    assert.deepEqual(bad.slice(0, 3).map((c) => ({
      text: c.text,
      python: c.expect.collector_number,
      phone: parseFooter(c.text).collectorNumber,
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });

  test('set code', () => {
    const bad = CORPUS.filter(
      (c) => parseFooter(c.text).setCode !== c.expect.set_code);
    assert.deepEqual(bad.slice(0, 3).map((c) => ({
      text: c.text,
      python: c.expect.set_code,
      phone: parseFooter(c.text).setCode,
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });

  test('foil hint', () => {
    // A false foil silently overvalues a collection, so this one is not
    // cosmetic.
    const bad = CORPUS.filter(
      (c) => parseFooter(c.text).foilHint !== c.expect.foil_hint);
    assert.equal(bad.length, 0, `${bad.length} disagreed, e.g. ${
      JSON.stringify(bad[0]?.text)}`);
  });

  test('every collector number found, in order', () => {
    const bad = CORPUS.filter((c) => {
      const mine = collectorNumbersIn(c.text).slice(0, 8);
      return JSON.stringify(mine) !== JSON.stringify(c.expect.numbers);
    });
    assert.deepEqual(bad.slice(0, 3).map((c) => ({
      text: c.text,
      python: c.expect.numbers,
      phone: collectorNumbersIn(c.text).slice(0, 8),
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });

  test('the (set, number) keys, in the same order', () => {
    // Order is the whole point: the first key that resolves wins, so a port
    // that finds the right pair second files the wrong card.
    const bad = CORPUS.filter((c) => {
      const mine = footerKeys(c.text).slice(0, 12).map((k) => [k[0], k[1]]);
      return JSON.stringify(mine) !== JSON.stringify(c.expect.footer_keys);
    });
    assert.deepEqual(bad.slice(0, 2).map((c) => ({
      text: c.text,
      python: c.expect.footer_keys,
      phone: footerKeys(c.text).slice(0, 12),
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });
});

/** A catalogue holding exactly the printings the corpus was built from. */
function catalogueOf(cases) {
  const byKey = new Map();
  for (const c of cases) {
    byKey.set(`${c.row.set_code.toLowerCase()} ${c.row.collector_number}`, c.row);
  }
  return {
    async printingByKey(setCode, number) {
      return byKey.get(`${setCode.toLowerCase()} ${number}`) ?? null;
    },
  };
}

describe('identifying end to end', () => {
  test('a clean read of a real card identifies it and may be filed', async () => {
    const catalogue = catalogueOf(CORPUS);
    // The clean rendering is every seventh case, by construction.
    const clean = CORPUS.filter((_, i) => i % 7 === 0);
    let identified = 0;
    for (const c of clean) {
      const out = await identifyLocally(c.text, catalogue);
      if (out.autoAddable && out.candidates[0]?.printing_id === c.row.printing_id) {
        identified += 1;
      }
    }
    // Not every printing has a footer that survives this shape — a collector
    // number like "js0b" does not sit in "js0b/264" the way a plain one
    // does. The bar is that the overwhelming majority do.
    assert.ok(identified / clean.length > 0.9,
      `only ${identified}/${clean.length} clean reads identified`);
  });

  test('a footer with no name above it is NOT auto-added', async () => {
    // A single misread digit lands on a different real printing, usually in
    // the same set. With no name to contradict it, a wrong key would sail
    // through as exact and file the wrong card silently.
    const catalogue = catalogueOf(CORPUS);
    const nameless = CORPUS.filter((_, i) => i % 7 === 6);
    for (const c of nameless.slice(0, 60)) {
      const out = await identifyLocally(c.text, catalogue);
      assert.equal(out.autoAddable, false,
        `filed ${c.row.name} on a footer with nothing confirming it`);
    }
  });

  test('and it still OFFERS the printing, so it is one tap not a retype',
    async () => {
      const catalogue = catalogueOf(CORPUS);
      const nameless = CORPUS.filter((_, i) => i % 7 === 6);
      const offered = [];
      for (const c of nameless.slice(0, 60)) {
        const out = await identifyLocally(c.text, catalogue);
        if (out.candidates.length) offered.push(c);
      }
      assert.ok(offered.length > 40,
        `only ${offered.length}/60 offered a candidate to tap`);
    });

  test('a card the index does not hold matches nothing rather than guessing',
    async () => {
      const empty = { async printingByKey() { return null; } };
      const out = await identifyLocally(
        'Sol Ring\n0410/0500 U\nCMM • EN', empty);
      assert.deepEqual(out.candidates, []);
      assert.equal(out.autoAddable, false);
      assert.match(out.reason, /matched no printing/);
    });

  test('unreadable text says so rather than blaming the index', async () => {
    const out = await identifyLocally('~~~ ¤¤¤ ~~~',
      { async printingByKey() { return null; } });
    assert.match(out.reason, /Could not read the set and number/);
  });
});

describe('a footer that prints the rarity first', () => {
  /**
   * From a real scan that would not go in: a Murders at Karlov Manor
   * prerelease promo, photographed well, in good light, filling the
   * frame. The app said "saw a card but could not place it".
   *
   * Its collector line reads
   *
   *     M 0200
   *     MKM(star)EN   Livia Prima
   *
   * and every pattern here wanted the rarity AFTER the number. With no
   * collector number parsed there was no key to look up, so a perfectly
   * readable card produced nothing at all. The set code came back fine,
   * which is exactly why it reported seeing a card rather than seeing
   * nothing.
   *
   * Whether the card prints it in that order or ML Kit returns the
   * blocks that way does not matter: the reading happens, and accepting
   * the rarity on either side costs nothing.
   */
  const FOOTER = ['Etrata, Deadly Fugitive', 'M 0200',
                  'MKM★EN  Livia Prima'].join('\n');

  test('the collector number is found', () => {
    assert.deepEqual(collectorNumbersIn(FOOTER), ['200']);
  });

  test('and it makes a key with the set', () => {
    assert.deepEqual(footerKeys(FOOTER), [['mkm', '200']]);
  });

  test('the star is still read as foil', () => {
    // It has always meant foil here, and a prerelease promo is foil.
    assert.equal(parseFooter(FOOTER).foilHint, true);
  });

  test('rarity after the number still works', () => {
    // The overwhelmingly common layout, and the regression guard.
    assert.deepEqual(
      collectorNumbersIn(['0200 M', 'MKM • EN'].join('\n')), ['200']);
  });

  test('a small number before a capital is NOT a collector number', () => {
    // Why the rarity-first form is restricted to the padded 3-4 digit
    // style: rules text is full of small numbers beside capitals, and
    // "R 3" must never become a lookup key.
    assert.deepEqual(collectorNumbersIn('Sacrifice a creature: R 3'), []);
    assert.deepEqual(collectorNumbersIn('Add C 2 to your mana pool'), []);
  });

  test('nor a year, which is the other four-digit number down there', () => {
    // "TM & (c) 2024 Wizards of the Coast" sits on the same footer, and
    // a stray capital beside it must not read as rarity plus number.
    assert.deepEqual(
      collectorNumbersIn('TM & © 2024 Wizards of the Coast'), []);
  });
});

describe('scanning a prerelease promo', () => {
  /**
   * A prerelease promo prints its ORIGINAL set code and number -- MKM,
   * 0200 -- and the catalogue files it somewhere else entirely, as
   * `pmkm` / `200s`. The only thing on the card distinguishing it from
   * the ordinary foil is the holofoil date stamp in the art, which is a
   * picture and not text, so OCR cannot tell them apart and never will.
   *
   * So the user tells it. The toggle turns the read key into the promo
   * key before the lookup; everything downstream is unchanged.
   *
   * The mapping was checked against the real catalogue rather than
   * assumed: of 3884 prerelease-style rows in p-prefixed sets, 3854 map
   * back to the same card in the base set under this exact rule. The 30
   * that do not are all Portal, whose set code simply begins with a p
   * and is not a promo set at all.
   */
  test('the promo key is the p-set and an s-suffixed number', () => {
    assert.deepEqual(promoKey('mkm', '200'), ['pmkm', '200s']);
  });

  test('a set code that already starts with p is still prefixed', () => {
    // `pstx` prerelease promos exist; a card printed "STX" maps to
    // `pstx`. Nothing printed on a card carries the p already, so this
    // is only ever about not special-casing the letter.
    assert.deepEqual(promoKey('stx', '90'), ['pstx', '90s']);
  });

  test('a number that already ends in s is left alone', () => {
    // Belt and braces: mapping twice must not produce "200ss".
    assert.deepEqual(promoKey('mkm', '200s'), ['pmkm', '200s']);
  });

  test('nothing to map without both halves', () => {
    assert.equal(promoKey('', '200'), null);
    assert.equal(promoKey('mkm', ''), null);
  });

  test('the promo printing is preferred when it exists', async () => {
    const seen = [];
    const catalogue = {
      async printingByKey(set, num) {
        seen.push(`${set}/${num}`);
        if (set === 'pmkm' && num === '200s') {
          return { printing_id: 'promo', name: 'Etrata, Deadly Fugitive',
                   set_code: 'pmkm', collector_number: '200s' };
        }
        return null;
      },
    };
    const out = await identifyLocally(
      ['Etrata, Deadly Fugitive', 'M 0200', 'MKM★EN'].join('\n'),
      catalogue, { preferPromo: true });

    assert.equal(out.autoAddable, true);
    assert.equal(out.candidates[0].printing_id, 'promo');
    assert.ok(seen.includes('pmkm/200s'), 'it should have asked for the promo');
  });

  test('and the ordinary printing is used when there is no promo', async () => {
    // A card the user flagged as a promo that has no promo printing.
    // Filing the regular one beats refusing a card that is plainly
    // there; the screen says which it used.
    const catalogue = {
      async printingByKey(set, num) {
        if (set === 'mkm' && num === '200') {
          return { printing_id: 'regular', name: 'Etrata, Deadly Fugitive',
                   set_code: 'mkm', collector_number: '200' };
        }
        return null;
      },
    };
    const out = await identifyLocally(
      ['Etrata, Deadly Fugitive', 'M 0200', 'MKM★EN'].join('\n'),
      catalogue, { preferPromo: true });

    assert.equal(out.autoAddable, true);
    assert.equal(out.candidates[0].printing_id, 'regular');
  });

  test('with the toggle off the promo is never reached', async () => {
    // The default, and the behaviour every other test in this file
    // depends on. Asking for the promo key unasked would quietly move
    // ordinary foils into the promo set.
    const seen = [];
    const catalogue = {
      async printingByKey(set, num) {
        seen.push(`${set}/${num}`);
        if (set === 'mkm' && num === '200') {
          return { printing_id: 'regular', name: 'Etrata, Deadly Fugitive',
                   set_code: 'mkm', collector_number: '200' };
        }
        return null;
      },
    };
    const out = await identifyLocally(
      ['Etrata, Deadly Fugitive', 'M 0200', 'MKM★EN'].join('\n'),
      catalogue);

    assert.equal(out.candidates[0].printing_id, 'regular');
    assert.deepEqual(seen.filter((k) => k.startsWith('pmkm')), []);
  });

  test('the name still has to agree, promo or not', async () => {
    // The corroboration rule is what stops a misread digit filing a
    // different real printing, and a promo lookup must not bypass it.
    const catalogue = {
      async printingByKey(set, num) {
        if (set === 'pmkm' && num === '200s') {
          return { printing_id: 'promo', name: 'Somebody Else Entirely',
                   set_code: 'pmkm', collector_number: '200s' };
        }
        return null;
      },
    };
    const out = await identifyLocally(
      ['Etrata, Deadly Fugitive', 'M 0200', 'MKM★EN'].join('\n'),
      catalogue, { preferPromo: true });

    assert.equal(out.autoAddable, false);
  });
});

describe('a power/toughness box that reads like a collector number', () => {
  /**
   * The Etrata scan, finally diagnosed by the app itself: "Read MKM #1,
   * which is not in this phone's index."
   *
   * The footer was read perfectly. `1/4` is the creature's
   * power/toughness, in the bottom-right box, and it is indistinguishable
   * from the old-style "49/264" collector number that the same pattern
   * exists to catch. So the keys come out as MKM #1 first and MKM #200
   * second.
   *
   * MKM #1 is a real printing. The lookup hit it, the name on the card
   * disagreed with it -- correctly -- and the search STOPPED there,
   * never reaching the key that was right all along.
   *
   * The desktop has the same early break and gets away with it, because
   * a failed key falls through to a fuzzy search by name. The phone has
   * no such fallback by design: exact key or nothing. So on the phone a
   * wrong-but-real key is fatal, and it must keep looking instead.
   */
  const ETRATA = [
    'Etrata, Deadly Fugitive',
    'Legendary Creature - Vampire Assassin',
    'Deathtouch',
    '1/4',
    'M 0200',
    'MKM★EN  Livia Prima',
  ].join('\n');

  const CATALOGUE = {
    async printingByKey(set, num) {
      if (set !== 'mkm') return null;
      if (num === '1') {
        return { printing_id: 'wrong', name: 'Absolutely Other Card',
                 set_code: 'mkm', collector_number: '1' };
      }
      if (num === '200') {
        return { printing_id: 'right', name: 'Etrata, Deadly Fugitive',
                 set_code: 'mkm', collector_number: '200' };
      }
      return null;
    },
  };

  test('the P/T is read as a collector number, as it always was', () => {
    // Not fixed here, deliberately: this pattern is shared with the
    // desktop and the 2800-case corpus pins it. The cure is to survive
    // it, not to narrow a regex the other implementation still has.
    assert.ok(collectorNumbersIn(ETRATA).includes('1'));
    assert.ok(collectorNumbersIn(ETRATA).includes('200'));
  });

  test('and the right card is still identified', async () => {
    const out = await identifyLocally(ETRATA, CATALOGUE);
    assert.equal(out.autoAddable, true);
    assert.equal(out.candidates[0].printing_id, 'right');
    assert.equal(out.identity.collectorNumber, '200');
  });

  test('a hit whose name disagrees does not end the search', async () => {
    // The mechanism, stated on its own so a future refactor cannot
    // quietly restore the early break.
    const asked = [];
    const watched = {
      async printingByKey(set, num) {
        asked.push(`${set}/${num}`);
        return CATALOGUE.printingByKey(set, num);
      },
    };
    await identifyLocally(ETRATA, watched);
    assert.ok(asked.includes('mkm/1'), 'it should have tried the P/T key');
    assert.ok(asked.includes('mkm/200'), 'and gone on to the real one');
  });

  test('when nothing corroborates, the first real hit is still offered',
    async () => {
      // Unchanged behaviour for the case this rule was written for: a
      // key that resolves but cannot be confirmed is shown to a person
      // rather than filed, and is one tap instead of a retype.
      const out = await identifyLocally(
        ['1/4', 'M 0200', 'MKM★EN'].join('\n'), CATALOGUE);
      assert.equal(out.autoAddable, false);
      assert.equal(out.candidates.length, 1);
      assert.match(out.reason, /could not be read|name/i);
    });

  test('and a corroborated FIRST key still wins immediately', async () => {
    // The common path must not get slower or change answer.
    const asked = [];
    const watched = {
      async printingByKey(set, num) {
        asked.push(`${set}/${num}`);
        if (set === 'mkm' && num === '1') {
          return { printing_id: 'right', name: 'Absolutely Other Card',
                   set_code: 'mkm', collector_number: '1' };
        }
        return null;
      },
    };
    const out = await identifyLocally(
      ['Absolutely Other Card', '1/4', 'MKM★EN'].join('\n'), watched);
    assert.equal(out.autoAddable, true);
    assert.deepEqual(asked, ['mkm/1'], 'it should have stopped at the hit');
  });
});

describe('when the footer cannot be read but the title can', () => {
  /**
   * Two real scans that came to nothing with the name sitting right
   * there at the top of the picture:
   *
   *   * an M11 Island. Cards printed before the 2014 frame carry NO set
   *     code at all -- there is a set symbol, which is a picture, and
   *     the copyright line. There is nothing to read, and no amount of
   *     light or zoom will produce a set code that was never printed.
   *     That is most of Magic's history.
   *   * a sleeved Lazav at an angle, whose collector line simply did
   *     not come back.
   *
   * The name did, both times, and `idx_cat_name` has existed since the
   * index was designed with the comment "the fallback, when the footer
   * is unreadable but the title is not". This is that fallback.
   *
   * Exact equality only, never fuzzy: a misread name matches nothing,
   * which is safe, while a fuzzy one matches the wrong card, which is
   * the entire class of error this matcher exists to avoid. The fuzzy
   * half stays on the desktop.
   *
   * It is worth having because of how the catalogue is shaped: 46% of
   * card names have exactly one printing and 77% have three or fewer,
   * so for most cards a name IS an identification. The exceptions are
   * the basic lands, with eight hundred printings each.
   */
  function catalogue(byName) {
    return {
      async printingByKey() { return null; },
      async printingsByName(name) { return byName[name] ?? []; },
    };
  }

  const LAZAV = { printing_id: 'rna-212', name: 'Lazav, the Multifarious',
                  set_code: 'rna', collector_number: '212' };

  test('a name with exactly one printing is identified outright', async () => {
    // No ambiguity to resolve: the name picks out one row in the whole
    // catalogue, which is a stronger claim than a footer key plus a
    // name that agrees.
    const out = await identifyLocally(
      'Lazav, the Multifarious\nLegendary Creature - Shapeshifter',
      catalogue({ 'Lazav, the Multifarious': [LAZAV] }));

    assert.equal(out.autoAddable, true);
    assert.equal(out.candidates[0].printing_id, 'rna-212');
  });

  test('a handful of printings are offered rather than guessed', async () => {
    const printings = [LAZAV, { ...LAZAV, printing_id: 'rvr-1', set_code: 'rvr' }];
    const out = await identifyLocally(
      'Lazav, the Multifarious',
      catalogue({ 'Lazav, the Multifarious': printings }));

    assert.equal(out.autoAddable, false, 'which printing is a real question');
    assert.equal(out.candidates.length, 2);
    assert.match(out.reason, /which printing|printings/i);
  });

  test('the sizes people actually scan are all offered', async () => {
    /*
     * Measured against the real catalogue, not guessed. Every one of
     * these is a card somebody tried to scan and was refused by a cap
     * of eight, with the answer plainly on the list:
     *
     *   Assassinate 9, Go for the Throat 16, Deadly Dispute 19,
     *   Royal Assassin 29.
     */
    for (const count of [9, 16, 19, 29, NAME_SHORTLIST]) {
      const rows = Array.from({ length: count }, (_, i) => ({
        printing_id: `p${i}`, name: 'Royal Assassin',
        set_code: 's', collector_number: String(i),
      }));
      const out = await identifyLocally(
        'Royal Assassin', catalogue({ 'Royal Assassin': rows }));
      assert.equal(out.candidates.length, count, `${count} printings`);
      assert.equal(out.autoAddable, false);
    }
  });

  test('eight hundred printings is not a pick list', async () => {
    // A basic Island. Offering the user 828 rows is not help, and
    // guessing one of them is worse.
    const islands = Array.from({ length: 828 }, (_, i) => ({
      printing_id: `i${i}`, name: 'Island',
      set_code: 's', collector_number: String(i),
    }));
    const out = await identifyLocally('Island\nBasic Land - Island',
                                      catalogue({ Island: islands }));

    assert.equal(out.autoAddable, false);
    assert.equal(out.candidates.length, 0, 'no useful shortlist exists');
    assert.match(out.reason, /828|too many/i);
  });

  test('a misread name matches nothing, which is the safe answer', async () => {
    // "Shapeshifrer" is what the recogniser actually returned. Exact
    // equality means a damaged name simply fails rather than landing on
    // a neighbour.
    const out = await identifyLocally(
      'Lazav, the Multifarous\nLegendary Creature - Shapeshifrer',
      catalogue({ 'Lazav, the Multifarious': [LAZAV] }));

    assert.equal(out.autoAddable, false);
    assert.equal(out.candidates.length, 0);
  });

  test('a good footer still wins and the names are never consulted',
    async () => {
      // The fallback must not slow down or second-guess the common path.
      let askedNames = 0;
      const cat = {
        async printingByKey(set, num) {
          return set === 'rna' && num === '212' ? LAZAV : null;
        },
        async printingsByName(name) { askedNames += 1; return []; },
      };
      const out = await identifyLocally(
        'Lazav, the Multifarious\n212 R\nRNA • EN', cat);

      assert.equal(out.autoAddable, true);
      assert.equal(askedNames, 0);
    });

  test('a name beats a footer key whose card disagreed', async () => {
    // The key resolved to a real but different printing, and the card
    // says its own name plainly. The name is the better evidence.
    const cat = {
      async printingByKey() {
        return { printing_id: 'wrong', name: 'Something Else',
                 set_code: 'rna', collector_number: '1' };
      },
      async printingsByName(name) {
        return name === 'Lazav, the Multifarious' ? [LAZAV] : [];
      },
    };
    const out = await identifyLocally(
      'Lazav, the Multifarious\n1/4\nRNA • EN', cat);

    assert.equal(out.autoAddable, true);
    assert.equal(out.candidates[0].printing_id, 'rna-212');
  });

  test('an index with no name lookup at all still works', async () => {
    // `printingsByName` is optional so every existing caller and fake
    // keeps working untouched.
    const out = await identifyLocally('Lazav, the Multifarious',
                                      { async printingByKey() { return null; } });
    assert.equal(out.autoAddable, false);
  });
});
