/**
 * The phone's matcher against the desktop's, case for case.
 *
 * `src/lib/identify.ts` is a port of the exact-key half of `scanner.py`, and
 * a port is only worth anything if it agrees with the original. The regexes
 * it carries are not decorative — each one records a card that was filed
 * wrong until it was fixed, and re-deriving them by eye on a second platform
 * is how you get those bugs back one at a time.
 *
 * So the expectations here are not hand-written. `fixtures/identify-corpus
 * .json` was generated by running the real Python functions over 400 real
 * printings from the real catalogue, in seven renderings each — clean, foil
 * star, separator eaten, bare number, mirrored OCR debris, a leading O for a
 * zero, and a footer with no name above it. If the two implementations ever
 * disagree about any of those, this fails.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, test } from 'node:test';

import {
  collectorNumbersIn,
  footerKeys,
  identifyLocally,
  looksLikeSetCode,
  normaliseNumber,
  parseFooter,
  repairDigits,
  setCodeVariants,
} from '../src/lib/identify.ts';

const load = (name) =>
  JSON.parse(readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf8'));

const CORPUS = load('identify-corpus.json');
const HELPERS = load('identify-helpers.json');

describe('the small pieces agree with Python', () => {
  test('collector numbers normalise identically', () => {
    for (const [input, expected] of Object.entries(HELPERS.normalise)) {
      assert.equal(normaliseNumber(input), expected, `normalise(${input})`);
    }
  });

  test('digit repair leaves words alone identically', () => {
    // The one that matters: "MID-2I1" must NOT become "M10-211", which is a
    // real PLST number for a different card and auto-added it.
    for (const [input, expected] of Object.entries(HELPERS.repair)) {
      assert.equal(repairDigits(input), expected, `repair(${input})`);
    }
  });

  test('set-code capitalisation is judged identically', () => {
    for (const [input, expected] of Object.entries(HELPERS.setcode)) {
      assert.equal(looksLikeSetCode(input), expected, `looksLike(${input})`);
    }
  });

  test('set-code variants are generated identically', () => {
    for (const [input, expected] of Object.entries(HELPERS.variants)) {
      assert.deepEqual(setCodeVariants(input), expected, `variants(${input})`);
    }
  });
});

describe('the footer parse agrees across 2800 real cases', () => {
  test('collector number', () => {
    const bad = CORPUS.filter(
      (c) => parseFooter(c.text).collectorNumber !== c.expect.collector_number);
    assert.deepEqual(bad.slice(0, 3).map((c) => ({
      text: c.text,
      python: c.expect.collector_number,
      phone: parseFooter(c.text).collectorNumber,
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });

  test('set code', () => {
    const bad = CORPUS.filter(
      (c) => parseFooter(c.text).setCode !== c.expect.set_code);
    assert.deepEqual(bad.slice(0, 3).map((c) => ({
      text: c.text,
      python: c.expect.set_code,
      phone: parseFooter(c.text).setCode,
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });

  test('foil hint', () => {
    // A false foil silently overvalues a collection, so this one is not
    // cosmetic.
    const bad = CORPUS.filter(
      (c) => parseFooter(c.text).foilHint !== c.expect.foil_hint);
    assert.equal(bad.length, 0, `${bad.length} disagreed, e.g. ${
      JSON.stringify(bad[0]?.text)}`);
  });

  test('every collector number found, in order', () => {
    const bad = CORPUS.filter((c) => {
      const mine = collectorNumbersIn(c.text).slice(0, 8);
      return JSON.stringify(mine) !== JSON.stringify(c.expect.numbers);
    });
    assert.deepEqual(bad.slice(0, 3).map((c) => ({
      text: c.text,
      python: c.expect.numbers,
      phone: collectorNumbersIn(c.text).slice(0, 8),
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });

  test('the (set, number) keys, in the same order', () => {
    // Order is the whole point: the first key that resolves wins, so a port
    // that finds the right pair second files the wrong card.
    const bad = CORPUS.filter((c) => {
      const mine = footerKeys(c.text).slice(0, 12).map((k) => [k[0], k[1]]);
      return JSON.stringify(mine) !== JSON.stringify(c.expect.footer_keys);
    });
    assert.deepEqual(bad.slice(0, 2).map((c) => ({
      text: c.text,
      python: c.expect.footer_keys,
      phone: footerKeys(c.text).slice(0, 12),
    })), [], `${bad.length} of ${CORPUS.length} disagreed`);
  });
});

/** A catalogue holding exactly the printings the corpus was built from. */
function catalogueOf(cases) {
  const byKey = new Map();
  for (const c of cases) {
    byKey.set(`${c.row.set_code.toLowerCase()} ${c.row.collector_number}`, c.row);
  }
  return {
    async printingByKey(setCode, number) {
      return byKey.get(`${setCode.toLowerCase()} ${number}`) ?? null;
    },
  };
}

describe('identifying end to end', () => {
  test('a clean read of a real card identifies it and may be filed', async () => {
    const catalogue = catalogueOf(CORPUS);
    // The clean rendering is every seventh case, by construction.
    const clean = CORPUS.filter((_, i) => i % 7 === 0);
    let identified = 0;
    for (const c of clean) {
      const out = await identifyLocally(c.text, catalogue);
      if (out.autoAddable && out.candidates[0]?.printing_id === c.row.printing_id) {
        identified += 1;
      }
    }
    // Not every printing has a footer that survives this shape — a collector
    // number like "js0b" does not sit in "js0b/264" the way a plain one
    // does. The bar is that the overwhelming majority do.
    assert.ok(identified / clean.length > 0.9,
      `only ${identified}/${clean.length} clean reads identified`);
  });

  test('a footer with no name above it is NOT auto-added', async () => {
    // A single misread digit lands on a different real printing, usually in
    // the same set. With no name to contradict it, a wrong key would sail
    // through as exact and file the wrong card silently.
    const catalogue = catalogueOf(CORPUS);
    const nameless = CORPUS.filter((_, i) => i % 7 === 6);
    for (const c of nameless.slice(0, 60)) {
      const out = await identifyLocally(c.text, catalogue);
      assert.equal(out.autoAddable, false,
        `filed ${c.row.name} on a footer with nothing confirming it`);
    }
  });

  test('and it still OFFERS the printing, so it is one tap not a retype',
    async () => {
      const catalogue = catalogueOf(CORPUS);
      const nameless = CORPUS.filter((_, i) => i % 7 === 6);
      const offered = [];
      for (const c of nameless.slice(0, 60)) {
        const out = await identifyLocally(c.text, catalogue);
        if (out.candidates.length) offered.push(c);
      }
      assert.ok(offered.length > 40,
        `only ${offered.length}/60 offered a candidate to tap`);
    });

  test('a card the index does not hold matches nothing rather than guessing',
    async () => {
      const empty = { async printingByKey() { return null; } };
      const out = await identifyLocally(
        'Sol Ring\n0410/0500 U\nCMM • EN', empty);
      assert.deepEqual(out.candidates, []);
      assert.equal(out.autoAddable, false);
      assert.match(out.reason, /matched no printing/);
    });

  test('unreadable text says so rather than blaming the index', async () => {
    const out = await identifyLocally('~~~ ¤¤¤ ~~~',
      { async printingByKey() { return null; } });
    assert.match(out.reason, /Could not read the set and number/);
  });
});
