/**
 * Drawing under the system bars.
 *
 * Android 15 forces edge-to-edge on anything targeting SDK 35 or above. That
 * is not a setting; it is the only mode. The app drew straight through it —
 * the offline banner sat behind the clock, and the tab bar behind the gesture
 * pill, because `SafeAreaView` from react-native does nothing at all on
 * Android. It is an iOS notch shim and always has been.
 *
 * The fix has two halves and needs both: the bars are hidden outright
 * (sticky-immersive, the way Table of War does it), and the layout still
 * respects whatever insets the system reports, because a swipe brings the
 * bars back on top of whatever is there and a punch-hole camera never goes
 * away at all.
 */

import { strict as assert } from 'node:assert';
import { existsSync, readFileSync } from 'node:fs';
import { describe, test } from 'node:test';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

// Comments here name the deprecated APIs in order to explain why they are not
// used, so a check that reads raw text finds the explanation and calls it the
// offence.
const code = (text) =>
  text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*(\/\/|\*).*$/gm, '');

describe('the app accounts for the system bars', () => {
  const app = read('../App.tsx');

  test('it does not use the SafeAreaView that does nothing on Android', () => {
    assert.ok(
      !/SafeAreaView/.test(code(app)),
      "react-native's SafeAreaView is an iOS-only shim",
    );
  });

  test('insets come from the provider that reports real ones', () => {
    assert.ok(app.includes('SafeAreaProvider'));
    assert.ok(app.includes('useSafeAreaInsets'));
  });

  test('the tab bar is padded away from the navigation buttons', () => {
    assert.match(app, /styles\.tabs,\s*\{\s*paddingBottom/);
  });

  test('the top has a floor under it', () => {
    // With the bars hidden the system reports nothing for them, but a
    // punch-hole camera is still there. Zero padding puts text under it.
    assert.match(app, /Math\.max\(insets\.top,/);
  });
});

describe('the immersive plugin', () => {
  const plugin = read('../plugins/with-immersive.cjs');

  test('it is CommonJS', () => {
    // package.json declares "type": "module", so a .js plugin is loaded as
    // ESM, `require` is undefined, and the plugin throws. Expo prints the
    // error and still exits 0 — a build that looks fine and applied nothing.
    assert.ok(plugin.includes('module.exports'));
  });

  test('app.json points at it by the name it actually has', () => {
    const config = JSON.parse(read('../app.json'));
    assert.ok(
      config.expo.plugins.includes('./plugins/with-immersive.cjs'),
      'app.json references a plugin path that does not exist',
    );
  });

  test('it refuses to apply silently', () => {
    // A config plugin whose anchor stops matching produces a normal-looking
    // build with none of the behaviour in it. Throwing is the only way that
    // becomes visible.
    assert.ok(plugin.includes('throw new Error'));
  });

  test('it uses the API that still works on SDK 35+', () => {
    // setSystemUiVisibility and IMMERSIVE_STICKY are deprecated to the point
    // of being no-ops there.
    assert.ok(plugin.includes('WindowInsetsControllerCompat'));
    assert.ok(plugin.includes('BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE'));
    assert.ok(!code(plugin).includes('setSystemUiVisibility'));
  });

  test('the generated activity carries it, when it has been generated', () => {
    // android/ is git-ignored and regenerated by prebuild, so this checks it
    // only when it is present — but when it is, this is the proof the plugin
    // ran rather than merely being configured.
    const activity =
      '../android/app/src/main/java/com/densanon/densadeck/MainActivity.kt';
    if (!existsSync(new URL(activity, import.meta.url))) return;
    const source = read(activity);
    assert.ok(source.includes('goImmersive()'), 'the plugin did not apply');
    assert.ok(source.includes('onWindowFocusChanged'));
  });
});


describe('reaching the desktop at all', () => {
  test('the cleartext plugin is registered', () => {
    const config = JSON.parse(read('../app.json'));
    assert.ok(
      config.expo.plugins.includes('./plugins/with-cleartext.cjs'),
      'without this a release build cannot make one plain-HTTP request',
    );
  });

  test('it fails loudly rather than shipping a mute app', () => {
    assert.ok(read('../plugins/with-cleartext.cjs').includes('throw new Error'));
  });

  test('the built manifest permits cleartext, when it has been built', () => {
    // Android 9 made cleartext default to off. Expo puts the permission in
    // the DEBUG manifest only, so the release build blocked every request
    // before it left the handset — which reads as "Offline" while sitting
    // next to the PC on the same Wi-Fi.
    const manifest = '../android/app/src/main/AndroidManifest.xml';
    if (!existsSync(new URL(manifest, import.meta.url))) return;
    assert.match(read(manifest), /android:usesCleartextTraffic="true"/);
  });
});
