"""The app icon, and the two ways it silently goes generic.

A logo is not an icon. From Android 8 every launcher masks the icon to its
own shape — circle, squircle, rounded square, teardrop — and an app that
ships only a legacy square gets it shrunk and dropped on a plate the launcher
picks. That is the generic-badge look, and no amount of redrawing the PNG
fixes it: the fix is shipping the two-layer adaptive icon Android asks for,
which this app did not have at all.

The other way is quieter. `android/` is generated by `expo prebuild`, so a
regenerate wipes hand-placed resources and restores the template's. The only
defence is app.json naming the images, which is why that is asserted here
too — a checked-in icon with no config is one prebuild away from gone.
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
COMPANION = ROOT / "companion"
RES = COMPANION / "android" / "app" / "src" / "main" / "res"
APK = (COMPANION / "android" / "app" / "build" / "outputs" / "apk" / "release"
       / "app-release.apk")

DENSITIES = ["mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi"]
# 108dp foreground, 48dp legacy, at each density's scale.
EXPECTED = {"mdpi": (108, 48), "hdpi": (162, 72), "xhdpi": (216, 96),
            "xxhdpi": (324, 144), "xxxhdpi": (432, 192)}


class TestTheSourceIcons:
    def test_the_adaptive_icon_exists_at_all(self):
        """Without this file Android uses the legacy square on a grey plate,
        however good the artwork is."""
        assert (RES / "mipmap-anydpi-v26" / "ic_launcher.xml").exists()
        assert (RES / "mipmap-anydpi-v26" / "ic_launcher_round.xml").exists()

    def test_it_names_a_foreground_and_a_background(self):
        body = (RES / "mipmap-anydpi-v26" / "ic_launcher.xml").read_text(
            encoding="utf-8")
        assert "<adaptive-icon" in body
        assert "ic_launcher_foreground" in body
        assert "@color/iconBackground" in body

    def test_the_background_colour_is_defined(self):
        # A layer-list referencing a colour that does not exist fails the
        # build; one referencing the wrong one is silently the wrong icon.
        colours = (RES / "values" / "colors.xml").read_text(encoding="utf-8")
        assert "iconBackground" in colours

    @pytest.mark.parametrize("density", DENSITIES)
    def test_every_density_has_both_layers(self, density):
        folder = RES / f"mipmap-{density}"
        assert (folder / "ic_launcher_foreground.png").exists()
        assert (folder / "ic_launcher.png").exists()
        assert (folder / "ic_launcher_round.png").exists()

    @pytest.mark.parametrize("density", DENSITIES)
    def test_the_sizes_are_right_for_the_density(self, density):
        from PIL import Image
        want_fg, want_legacy = EXPECTED[density]
        folder = RES / f"mipmap-{density}"
        assert Image.open(folder / "ic_launcher_foreground.png").size == (
            want_fg, want_fg)
        assert Image.open(folder / "ic_launcher.png").size == (
            want_legacy, want_legacy)

    @pytest.mark.parametrize("density", DENSITIES)
    def test_no_webp_is_left_to_collide(self, density):
        # Two resources of the same name and different extensions in one
        # folder is a build error, and the template shipped .webp.
        folder = RES / f"mipmap-{density}"
        assert not (folder / "ic_launcher.webp").exists()
        assert not (folder / "ic_launcher_round.webp").exists()
        # The foreground too, and it is the one that actually bit: a
        # non-clean prebuild wrote ic_launcher_foreground.webp beside the
        # generated .png and AGP failed the release build on it. Checking
        # only the other two let that through.
        assert not (folder / "ic_launcher_foreground.webp").exists()

    def test_the_foreground_keeps_clear_of_the_mask(self):
        """Only the middle 66/108 of an adaptive icon survives every mask.

        Art outside it is clipped on some launchers and not others, which is
        the kind of bug that only shows up on someone else's phone.
        """
        from PIL import Image, ImageDraw

        fg = Image.open(RES / "mipmap-xxxhdpi" / "ic_launcher_foreground.png")
        alpha = fg.getchannel("A")
        canvas = fg.size[0]

        mask = Image.new("L", fg.size, 0)
        inset = canvas * (1 - 66 / 108) / 2
        ImageDraw.Draw(mask).ellipse(
            (inset, inset, canvas - inset - 1, canvas - inset - 1), fill=255)

        total = sum(alpha.getdata())
        kept = Image.new("L", fg.size, 0)
        kept.paste(alpha, (0, 0), mask)
        survived = sum(kept.getdata())
        assert total > 0, "the foreground is empty"
        assert (total - survived) / total < 0.01, (
            "art falls outside the safe circle and some launchers will clip it")

    def test_the_foreground_is_actually_the_artwork(self):
        """It was, briefly, a white silhouette — the trim returned the alpha
        channel instead of the image, and every icon came out a pale ghost
        with the red and black gone. Nothing about that throws."""
        from PIL import Image

        fg = Image.open(RES / "mipmap-xxxhdpi" / "ic_launcher_foreground.png")
        opaque = [p for p in fg.convert("RGBA").getdata() if p[3] > 200]
        assert opaque, "nothing opaque in the foreground"
        reds = sum(1 for r, g, b, _ in opaque if r > 120 and g < 90 and b < 90)
        darks = sum(1 for r, g, b, _ in opaque if r < 80 and g < 80 and b < 80)
        assert reds > len(opaque) * 0.05, "the red is missing"
        assert darks > len(opaque) * 0.05, "the black is missing"


class TestAPrebuildCannotQuietlyUndoIt:
    """`android/` is generated. Without app.json naming the images, the next
    `expo prebuild` restores the template icons and the work is gone with no
    error anywhere."""

    def _config(self) -> dict:
        return json.loads((COMPANION / "app.json").read_text(encoding="utf-8"))["expo"]

    def test_app_json_names_the_icon(self):
        assert self._config()["icon"] == "./assets/icon.png"

    def test_app_json_names_the_adaptive_foreground(self):
        adaptive = self._config()["android"]["adaptiveIcon"]
        assert adaptive["foregroundImage"] == "./assets/adaptive-icon.png"
        assert adaptive["backgroundColor"].upper() == "#F7F7F9"

    def test_the_images_it_names_are_there(self):
        assert (COMPANION / "assets" / "icon.png").exists()
        assert (COMPANION / "assets" / "adaptive-icon.png").exists()


class TestWhatActuallyShipped:
    """The built APK, because the resources are what matter and they are
    name-obfuscated in a release build — so this asks aapt, not the tree."""

    def test_the_manifest_points_at_an_adaptive_icon(self):
        if not APK.exists():
            pytest.skip("no release APK built")
        with zipfile.ZipFile(APK) as archive:
            names = archive.namelist()
        # An adaptive icon is an XML that applies at every density; a legacy
        # one is a PNG per density. The distinction is the whole feature.
        assert any(n.startswith("res/") and n.endswith(".xml") for n in names)

    def test_the_desktop_icon_carries_every_size_windows_asks_for(self):
        from PIL import Image
        ico = Image.open(ROOT / "assets" / "densa-deck.ico")
        sizes = set(ico.info.get("sizes", []))
        # 16 is the titlebar, 32 the taskbar, 256 the large-icon view. A .ico
        # missing a size gets one scaled by Windows, which looks it.
        assert {(16, 16), (32, 32), (48, 48), (256, 256)} <= sizes
