/**
 * Identifying a card on the phone, with no PC in reach.
 *
 * A port of the exact-key half of the desktop's `scanner.py`. Deliberately
 * only that half. The desktop also matches by name, fuzzily, through a
 * catalogue of 37,000 titles; that logic is where the wrong answers live and
 * it is the part with the scar tissue. Rather than reproduce it from memory
 * on a second platform, the phone does the one thing it can do exactly —
 * read the footer, look up the printing, and require the card's own name to
 * agree — and hands everything else to the PC.
 *
 * So the rule here is: match exactly, or do not match. A card this cannot
 * place is queued for the desktop, which is no worse than before and is
 * never a wrong card filed silently.
 *
 * Every regex, threshold and repair below is carried across verbatim from
 * the Python, comments included where they record why. `tests/identify-
 * conformance.test.mjs` checks this against cases generated by running the
 * real Python implementation over the real catalogue, so a drift between
 * the two shows up as a failure rather than as a card filed wrong.
 */

/** What we managed to read off a card face. */
export interface ReadIdentity {
  name: string;
  setCode: string;
  collectorNumber: string;
  foilHint: boolean;
}

export interface CataloguePrintingRow {
  printing_id: string;
  name: string;
  set_code: string;
  collector_number: string;
}

/** Somewhere to look printings up — the phone's own index, in practice. */
export interface LocalCatalogue {
  printingByKey(
    setCode: string,
    collectorNumber: string,
  ): Promise<CataloguePrintingRow | null>;
}

export interface LocalIdentifyResult {
  identity: ReadIdentity;
  candidates: CataloguePrintingRow[];
  /** Only ever true for an exact key the card's own name corroborates. */
  autoAddable: boolean;
  /** Why it is not auto-addable, in words a person can act on. */
  reason: string;
}

// Languages actually printed on Magic cards. Anchoring the set-code match on
// a closed list is what lets the separator be optional: OCR frequently drops
// the bullet and returns "DTK EN".
const LANGUAGES = [
  'EN', 'DE', 'FR', 'IT', 'ES', 'PT', 'JA', 'JP', 'KO', 'KR',
  'RU', 'ZH', 'CS', 'CT', 'CN', 'PH', 'LA', 'AR', 'HE',
];
const LANG_ALT = LANGUAGES.join('|');

// Separators seen between the set code and the language. The star forms
// matter: a promo/foil prints "DTK ★ EN", and omitting the star meant every
// promo fell back to guessing by name — exactly the sort of card people scan
// for its value. OCR renders these as an asterisk, a bullet or a dot.
const SEPARATORS = '[•·∙\\*★☆✦✧◆◇·\\.]';

// The left side is deliberately wider than "digits". Real collector numbers
// include "90", "90a", "★90", "WWK-90" (The List), "et208" (promos), "js0b"
// (World Championship decks) and "A25-181".
const COLLECTOR_RE =
  /(?<![\w/])([A-Z0-9]{1,6}(?:-[A-Z0-9]{1,6})?[a-z★]?)\s*\/\s*\d{1,4}(?![\d/])/gi;
const COLLECTOR_BARE_RE = /(?<![\w/])(\d{1,4}[a-z★]?)\s+[CURMLST](?![\w])/g;

const SET_LANG_RE = new RegExp(
  `\\b([0-9A-Z]{3,6})\\s*(?:${SEPARATORS}\\s*)?(${LANG_ALT})\\b`, 'gi');
const SET_ONLY_RE = new RegExp(`\\b([A-Z0-9]{3,6})\\s*${SEPARATORS}`);

// Measured against Windows OCR the star NEVER comes back as "★": on a clean
// render it vanishes, on a warped crop it becomes "*". The bullet survives
// reliably, so a bullet anywhere VETOES the foil reading — a misread bullet
// is the only way this produces a false foil, and a false foil silently
// overvalues someone's collection.
const FOIL_STAR_RE = new RegExp(
  `\\b[0-9A-Z]{3,6}\\s*[★☆✦✧\\*]\\s*(?:${LANG_ALT})\\b`);
const NONFOIL_BULLET_RE = new RegExp(
  `\\b[0-9A-Z]{3,6}\\s*[•·∙]\\s*(?:${LANG_ALT})\\b`);

// OCR routinely confuses these inside otherwise-numeric fields. D and Q are
// deliberately absent: they were here as 0-lookalikes and cost a real card.
// "MID-2I1" repaired to "M10-211", a genuine PLST number for a different
// card entirely, and auto-added it.
const LOOKALIKES: Record<string, string> = {
  O: '0', o: '0', ø: '0', Ø: '0',
  I: '1', l: '1', '|': '1', '!': '1',
  S: '5', s: '5', B: '8', Z: '2', G: '6',
};

/** Collector numbers as Scryfall stores them. */
export function normaliseNumber(raw: string): string {
  const value = (raw || '').trim().toLowerCase();
  if (!value) return '';
  // Leading zeros go ("0079" is 79) but a trailing letter stays — "123a" and
  // "123b" are genuinely different printings. Only for purely numeric ones:
  // "js0b" and "a25-181" must survive intact.
  const m = /^0*(\d+)([a-z★]?)$/.exec(value);
  return m ? `${m[1] ?? ''}${m[2] ?? ''}` : value;
}

/**
 * Text with digit-lookalike glyphs normalised, for numeric matching only.
 *
 * Token by token, and only where the token already looks like a number.
 * Translating the whole string flattened the alphabetic half of set-prefixed
 * collector numbers — "MID-2I1" became "M1D-211" and stopped resolving.
 */
export function repairDigits(text: string): string {
  return (text || '')
    .split(/([^0-9A-Za-zøØ|!]+)/)
    .map((token) => {
      const digits = (token.match(/\d/g) ?? []).length;
      const alnum = (token.match(/[0-9A-Za-z]/g) ?? []).length;
      // A token already half digits is a number OCR damaged; anything else
      // is a word, and words must survive intact.
      if (alnum && digits * 2 >= alnum) {
        return token.replace(/[OoøØIl|!SsBZG]/g, (c) => LOOKALIKES[c] ?? c);
      }
      return token;
    })
    .join('');
}

/**
 * Whether a token is capitalised the way a printed set code is.
 *
 * The guard that makes case-insensitive matching safe. Without it "Invade
 * the City" parses as the set "INVA" in German, trims to "INV" — Invasion, a
 * real set — and files a Pincer Spider under a card the user never owned.
 * The catalogue cannot arbitrate these: 411 of 986 set codes are three
 * letters, so a trimmed English word hits a real set routinely.
 */
export function looksLikeSetCode(raw: string): boolean {
  const letters = [...(raw || '')].filter((c) => /[a-z]/i.test(c));
  if (!letters.length) return !!raw;
  const upper = letters.filter((c) => c === c.toUpperCase()).length;
  return upper * 2 >= letters.length;
}

/** Every collector number the text plausibly contains, in reading order. */
export function collectorNumbersIn(text: string): string[] {
  const out: string[] = [];
  for (const candidate of [text || '', repairDigits(text || '')]) {
    for (const pattern of [COLLECTOR_RE, COLLECTOR_BARE_RE]) {
      pattern.lastIndex = 0;
      for (const m of candidate.matchAll(pattern)) {
        const number = normaliseNumber(m[1] ?? '');
        if (number && !out.includes(number)) out.push(number);
      }
    }
  }
  return out;
}

/** Where the collector number sits in the text, or -1. */
export function collectorPosition(text: string): number {
  for (const candidate of [text || '', repairDigits(text || '')]) {
    for (const pattern of [COLLECTOR_RE, COLLECTOR_BARE_RE]) {
      pattern.lastIndex = 0;
      const m = pattern.exec(candidate);
      if (m) return m.index;
    }
  }
  return -1;
}

/**
 * Every token that could be a set code, nearest the collector number first.
 *
 * Ordering matters because a token pulled out of flavour text can resolve to
 * a real set by coincidence. On a real card the set code is printed directly
 * beneath the collector number, so distance is a genuine signal.
 */
export function setCodesIn(text: string, near = -1): string[] {
  const matches: Array<[number, string]> = [];
  SET_LANG_RE.lastIndex = 0;
  for (const m of (text || '').matchAll(SET_LANG_RE)) {
    const raw = (m[1] || '').trim();
    if (raw && looksLikeSetCode(raw)) {
      matches.push([near >= 0 ? Math.abs((m.index ?? 0) - near) : 0,
        raw.toLowerCase()]);
    }
  }
  matches.sort((a, b) => a[0] - b[0]);

  const codes: string[] = [];
  for (const [, code] of matches) if (!codes.includes(code)) codes.push(code);
  if (!codes.length) {
    const m = SET_ONLY_RE.exec(text || '');
    if (m) codes.push((m[1] ?? '').trim().toLowerCase());
  }
  return codes;
}

/**
 * Spellings of one OCR'd set code to try, as-read first.
 *
 * OCR merges the separator into the code: a real photo of a foil DTK card
 * read "DtKtEN", which parses as "DTKT" — one character of debris from the
 * truth. Nothing here decides an identity; every spelling is looked up at
 * the collector number read alongside it, and only one that resolves lives.
 */
export function setCodeVariants(code: string): string[] {
  const value = (code || '').trim().toLowerCase();
  if (!value) return [];
  const variants = [value];
  for (const length of [5, 4, 3]) {
    if (value.length > length && !variants.includes(value.slice(0, length))) {
      variants.push(value.slice(0, length));
    }
  }
  return variants;
}

/**
 * Every (set, number) pair the text plausibly contains, best first.
 *
 * Single lines come first because a real footer key lives entirely on one
 * line, whereas a whole-text parse will happily pair a number from one line
 * with a set code from another.
 */
export function footerKeys(text: string): Array<[string, string]> {
  const keys: Array<[string, string]> = [];
  const seen = new Set<string>();
  const lines = (text || '').split(/\r?\n/);
  for (const chunk of [...lines, text || '']) {
    const numbers = collectorNumbersIn(chunk);
    if (!numbers.length) continue;
    for (const code of setCodesIn(chunk, collectorPosition(chunk))) {
      for (const variant of setCodeVariants(code)) {
        for (const number of numbers) {
          const key = `${variant} ${number}`;
          if (!seen.has(key)) {
            seen.add(key);
            keys.push([variant, number]);
          }
        }
      }
    }
  }
  return keys;
}

/** Pull collector number, set code and foil hint out of OCR text. */
export function parseFooter(text: string): ReadIdentity {
  const identity: ReadIdentity = {
    name: '', setCode: '', collectorNumber: '', foilHint: false,
  };
  if (!text) return identity;

  for (const candidate of [text, repairDigits(text)]) {
    COLLECTOR_RE.lastIndex = 0;
    const m = COLLECTOR_RE.exec(candidate);
    if (m) { identity.collectorNumber = normaliseNumber(m[1] ?? ''); break; }
    COLLECTOR_BARE_RE.lastIndex = 0;
    const bare = COLLECTOR_BARE_RE.exec(candidate);
    if (bare) { identity.collectorNumber = normaliseNumber(bare[1] ?? ''); break; }
  }

  identity.foilHint = FOIL_STAR_RE.test(text) && !NONFOIL_BULLET_RE.test(text);

  SET_LANG_RE.lastIndex = 0;
  for (const m of text.matchAll(SET_LANG_RE)) {
    if (looksLikeSetCode((m[1] || '').trim())) {
      identity.setCode = (m[1] || '').trim().toLowerCase();
      break;
    }
  }
  if (!identity.setCode) {
    const m = SET_ONLY_RE.exec(text);
    if (m) identity.setCode = (m[1] ?? '').trim().toLowerCase();
  }
  return identity;
}

/** Loose enough for OCR, strict enough to mean agreement. */
export function namesRoughlyMatch(a: string, b: string): boolean {
  const clean = (s: string) =>
    (s || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  const left = clean(a);
  const right = clean(b);
  if (!left || !right) return false;
  if (left === right) return true;
  // A face name is the front half of a "//" card, which is all OCR can read.
  const front = clean(right.split('//')[0] ?? '');
  return !!front && left === front;
}

/** Every line that might be the card's name. */
export function readableNames(text: string): string[] {
  return (text || '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

/**
 * Identify a card from OCR text against the phone's own index.
 *
 * Exact keys only, and only with corroboration. A footer key is specific,
 * which is why it looks trustworthy — but a single misread digit lands on a
 * DIFFERENT REAL PRINTING, usually in the same set. So the card has to say
 * its own name and that name has to agree before anything is filed without
 * a person looking at it.
 */
export async function identifyLocally(
  text: string,
  catalogue: LocalCatalogue,
): Promise<LocalIdentifyResult> {
  const identity = parseFooter(text);
  const names = readableNames(text);

  for (const [setCode, number] of footerKeys(text)) {
    const hit = await catalogue.printingByKey(setCode, number);
    if (!hit) continue;

    identity.setCode = setCode;
    identity.collectorNumber = number;

    // A name that resolves to a DIFFERENT card is a contradiction worth
    // stopping for. Junk matches nothing and must not veto a good read,
    // which is why this turns on agreement rather than on any name existing.
    const corroborated = names.some((n) => namesRoughlyMatch(n, hit.name));
    if (!corroborated) {
      return {
        identity, candidates: [hit], autoAddable: false,
        reason: `${setCode.toUpperCase()} #${number} reads as `
          + `'${hit.name}', but the card's name could not be read to `
          + 'confirm it',
      };
    }
    return { identity, candidates: [hit], autoAddable: true, reason: '' };
  }

  return {
    identity,
    candidates: [],
    autoAddable: false,
    // Said plainly, because the honest answer here is "ask the PC" and the
    // person should know that is what is happening.
    reason: identity.collectorNumber || identity.setCode
      ? 'Read part of the footer but matched no printing.'
      : 'Could not read the set and number off this card.',
  };
}
